[package]
name = "csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "1.3"
tabled = { version = "0.12", features = ["color"] }
serde = "1.0.163"
serde_json = "1.0.96"
